Algoritmo "Estrutura de repetição PARA exercício2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Marcos Monteiro
//Multiplos de 2 no intervalo de 0 a 100
Var
   j:inteiro

Inicio
   escreval("Monstrando os números múltiplos de 2 no intervalo de 0 a 100")
   para j de 0 ate 100 faca
      se(j mod 2)=0 entao
         escreval(j)
      senao
         escreva()
      fimse

   fimpara

Fimalgoritmo