Algoritmo "Exercício 1"
//Calculo de IMC - IMC=PESO/(ALTURA*ALTURA)

Var
   Nome:CARACTERE
   Peso, Altura,IMC:REAL

Inicio
   escreva("Digite o nome:")
   leia(Nome)
   escreva("Digite a altura:")
   leia(Altura)
   escreva("Digite o peso:")
   leia(Peso)
   IMC<- Peso/(Altura*Altura)))
   escreva("Nome: ",Nome," " ,"Altura:", Altura," mts ","Peso",Peso,"kgs ")
   escreva("IMC: ",IMC)
Fimalgoritmo